title: B-fun
description: > # this means to ignore newlines until "baseurl:"
  Evenementiel
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laberomain.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "/assets/images/logo.png"

google_site_verification: 

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/SCBeauvechain

# Build settings
markdown: kramdown
permalink: pretty