title: Gods Own Country Films
description: > # this means to ignore newlines until "baseurl:"
  Europe's leading film distributor for Mollywood
baseurl: "" # the subpath of your site, e.g. /blog
url: "godsowncountryfilms.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: Gods Own Country Films
  link: "https://www.facebook.com/godsowncountryfilms"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/godsowncountryfilms


# Build settings
markdown: kramdown
permalink: pretty
