title: IOL Yongin 2019
description: > # this means to ignore newlines until "baseurl:"
  The official website of the 17th International Linguistics Olympiad, Yongin, Korea. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "2019.ioling.org" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2019_style/img/icon-large.png"
background-image: "/css/2019_style/img/hufs.jpg"

social: 
  name: IOL 2019 Facebook
  link: "https://www.facebook.com/iol2019"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_2019_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/iol2019
  - title: twitter
    url: https://twitter.com/iol2019
  - title: envelope
    url: mailto:iol2019@krlo.kr

# Build settings
markdown: kramdown
permalink: pretty